steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/marketprobe-automation/marketprobe-pipeline', '-f', 'Dockerfile', '.']
images:
  - 'gcr.io/marketprobe-automation/marketprobe-pipeline'
