steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/marketprobe-automation/pipeline/scripts:latest', '-f', 'Dockerfile', '.']
images:
  - 'asia-northeast1-docker.pkg.dev/marketprobe-automation/pipeline/scripts:latest'
